Dashboard frontend navigation bar
HackYourFuture-CPH/team26-checkin pull request #22
Opened 2024-04-11 13:30 UTC by rumana-aafrin

# Description

This PR is about the left and top navigation bar in the dashboard page. It is working fine.

# How to test?

http://localhost:3000/dashboard

# Checklist

- [yes] I have performed a self-review of my own code
- [yes] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [yes] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [yes] This PR is ready to be merged and not breaking any other functionality

![image](https://github.com/HackYourFuture-CPH/team26-checkin/assets/70215401/182f84f2-0d98-4a05-98da-8f4c79f7e3a0)

2024-04-12 15:03 UTC, ddobby94 reviewed
Good progress :)

2024-04-12 15:03 UTC, ddobby94 commented on packages/client/src/App.js
> +// /* eslint-disable */
Please delete this unused comment. Or if you need the `eslint-disable` you should use it like this:
`/* eslint-disable */`

2024-04-12 15:03 UTC, ddobby94 commented on packages/client/src/App.js
> +// import { LandingPageContainer } from './containers/LandingPage/LandingPage';
If this is temporary you can show it in the comment. For example:
```
// TODO: put back comment after the login flow is down
// import { LandingPageContainer } from './containers/LandingPage/LandingPage';
```

2024-04-12 15:03 UTC, ddobby94 commented on packages/client/src/components/Dashboard/NavigationBar.jsx
> +          <div className="menu-icon" key={item.id}>
This should be a button, since we will be clicking on the navigation items :)

2024-04-12 15:03 UTC, ddobby94 commented on packages/client/src/components/Dashboard/NavigationBar.jsx
> +          <Typography variant="body1">Log out</Typography>
Same here, this should be a button.
It is very important for accessibility to use buttons for clickable elements always(!)

2024-04-12 15:03 UTC, ddobby94 commented on packages/client/src/components/Dashboard/NavigationBar.jsx
> +const navigationData = [
There is no need for an extra abstaction here, we can just use the navigation items directly in the NavigationBar

2024-04-12 15:03 UTC, ddobby94 commented on packages/client/src/containers/Dashboard/Dashboard.js
> +      <div className="left-nav-bar-container">
This should be in the `NavigationBar`

2024-04-16 17:46 UTC, shpomp requested changes
- Remove the commented-out code and the comments. 🙏🏽 

The comments are needed for more complex or non-self-explanatory cases, which is not the situation here. You don't need something like this: 

> // Prop validation for NavigationItem component
NavigationItem.propTypes = {

It is clear from the code itself and good naming what it is. 
If this is leftovers from AI assistance, carefully check the code before you submit it, make sure it is clean and that you are fully acquainted with it

- Additionally, you will need to address build fails. 
You can ignore the migrations for now, but others are simple fixable problems, just ask if you are in doubt. 🙏🏽

2024-04-16 19:36 UTC, rumana-aafrin commented
> * Remove the commented-out code and the comments. 🙏🏽
> 
> The comments are needed for more complex or non -elf-explanatory cases, which is not the situation here. You don't need something like this:
> 
> > // Prop validation for NavigationItem component
> > NavigationItem.propTypes = {
> 
> It is clear from the code itself and good naming what it is. If this is leftovers from AI assistance, carefully check the code before you submit it, make sure it is clean and that you are fully acquainted with it
> 
> * Additionally, you will need to address build fails.
>   You can ignore the migrations for now, but others are simple fixable problems, just ask if you are in doubt. 🙏🏽



> * Remove the commented-out code and the comments. 🙏🏽
> 
> The comments are needed for more complex or non -elf-explanatory cases, which is not the situation here. You don't need something like this:
> 
> > // Prop validation for NavigationItem component
> > NavigationItem.propTypes = {
> 
> It is clear from the code itself and good naming what it is. If this is leftovers from AI assistance, carefully check the code before you submit it, make sure it is clean and that you are fully acquainted with it
> 
> * Additionally, you will need to address build fails.
>   You can ignore the migrations for now, but others are simple fixable problems, just ask if you are in doubt. 🙏🏽


Thanks for pointing out @shpomp. Yes, I didn't notice the left out commented lines. Fixed it and got stuck with the git problems. Hoping to fix it soon!
I will check the workflow files to get checked!

2024-04-17 12:43 UTC, ddobby94 approved these changes
@shpomp please leave an approve so we can merge it 🙏

2024-04-17 12:56 UTC, ddobby94 commented on packages/client/src/App.js
> +// TODO: put back comment after the Dashboard backend flow is down
```suggestion
```

2024-04-17 12:56 UTC, ddobby94 commented on packages/client/src/App.js
> +// import { Dashboard }from './containers/Dashboard/Dashboard';
```suggestion
```

2024-04-17 13:24 UTC, shpomp requested changes
@ddobby94 @rumana-aafrin 
Would you address the build fail or we leave it for now?

2024-04-17 15:09 UTC, rumana-aafrin commented
> @ddobby94 @rumana-aafrin Would you address the build fail or we leave it for now?

I verified with the node version(as we fixed initially) but didn't address anything other than that. I think we can leave it for now due to shortage of time. And this is the main navbar design which is reused in all the pages. Teammates are also waiting to combine their work. 
Good to merge as soon as possible🙏

2024-04-17 16:06 UTC, shpomp approved these changes
⭐

2024-04-17 19:57 UTC, merged